name: Build, Version and Release

on:
  push:
    branches: [ main, test-actions ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Determine version
      id: versioning
      run: |
        # Get current version from the main script or default to 0.1.0
        CURRENT_VERSION=$(grep -o 'VERSION = "[^"]*"' main.py 2>/dev/null | cut -d'"' -f2 || echo "0.1.0")
        
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          # If this is a tag, use the tag name as version
          VERSION=${GITHUB_REF#refs/tags/v}
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          # For manual workflow, use the specified bump type
          BUMP_TYPE="${{ github.event.inputs.version_bump }}"
          
          # Parse version components (assuming format like 0.0.3)
          if [[ $CURRENT_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            
            # Apply version bump
            if [ "$BUMP_TYPE" == "major" ]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
            elif [ "$BUMP_TYPE" == "minor" ]; then
              MINOR=$((MINOR + 1))
              PATCH=0
            else
              PATCH=$((PATCH + 1))
            fi
            
            VERSION="$MAJOR.$MINOR.$PATCH"
          else
            # If version doesn't match expected format, use date-based version
            VERSION=$(date +'%Y.%m.%d.%H%M')
          fi
        else
          # For regular push, use the date-based version
          VERSION=$(date +'%Y.%m.%d.%H%M')
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Create version file
        mkdir -p config
        echo '"""Application version information."""' > config/version.py
        echo "" >> config/version.py
        echo "from __future__ import annotations" >> config/version.py
        echo "" >> config/version.py
        echo "__version__ = \"$VERSION\"" >> config/version.py
        echo "__build_date__ = \"$(date +'%Y-%m-%d')\"" >> config/version.py
        
        # Update version in main script
        if [ -f "main.py" ]; then
          sed -i "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" main.py
        fi
    
    - name: Upload version artifact
      uses: actions/upload-artifact@v4
      with:
        name: version-info
        path: |
          config/version.py
          main.py

  build-windows:
    needs: determine-version
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Download version info
      uses: actions/download-artifact@v4
      with:
        name: version-info
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean ChronicleAndroidRawDataPreprocessingApp.spec
    
    - name: Test executable startup time
      run: |
        $exePath = "dist\ChronicleAndroidRawDataPreprocessingApp\ChronicleAndroidRawDataPreprocessingApp.exe"
        
        # Check if the executable exists
        if (-not (Test-Path $exePath)) {
          Write-Error "Executable not found at: $exePath"
          exit 1
        }
        
        Write-Host "Testing executable startup time..."
        
        # Create a PowerShell script to measure startup time with proper error handling
        $measureScript = @"
        try {
          `$start = Get-Date
          Write-Host "Starting process: $exePath"
          
          # Start process and capture output to avoid UI issues in CI
          `$processInfo = New-Object System.Diagnostics.ProcessStartInfo
          `$processInfo.FileName = "$exePath"
          `$processInfo.RedirectStandardOutput = `$true
          `$processInfo.RedirectStandardError = `$true
          `$processInfo.UseShellExecute = `$false
          `$processInfo.CreateNoWindow = `$false
          
          `$process = New-Object System.Diagnostics.Process
          `$process.StartInfo = `$processInfo
          `$process.Start() | Out-Null
          
          Write-Host "Process started with PID: `$(`$process.Id)"
          
          # Non-blocking check for process existence
          `$startTime = Get-Date
          `$maxWaitTime = 15  # Maximum seconds to wait
          `$processStarted = `$false
          
          while ((Get-Date) -lt `$startTime.AddSeconds(`$maxWaitTime)) {
            # Check if process is still running
            if (`$process.HasExited) {
              Write-Host "Process exited prematurely with code: `$(`$process.ExitCode)"
              exit 1
            }
            
            # Process exists, consider it started
            `$processStarted = `$true
            `$end = Get-Date
            `$duration = (`$end - `$start).TotalSeconds
            Write-Host "Application started in `$duration seconds"
            break
          }
          
          if (-not `$processStarted) {
            Write-Host "ERROR: Timeout waiting for application to start"
            # Force kill the process if it's still running
            if (-not `$process.HasExited) {
              Write-Host "Killing unresponsive process"
              `$process.Kill()
            }
            exit 1
          }
          
          # Give it a moment to initialize
          Start-Sleep -Seconds 1
          
          # End the process
          if (-not `$process.HasExited) {
            Write-Host "Terminating process"
            `$process.Kill()
          }
          
          `$duration = (`$end - `$start).TotalSeconds
          if (`$duration -gt 10) {
            Write-Host "WARNING: Startup time exceeds 10 seconds (`$duration seconds)"
            exit 2
          }
          
          Write-Host "Test completed successfully. Startup time: `$duration seconds"
          exit 0
        }
        catch {
          Write-Host "ERROR: `$_"
          Get-Process | Where-Object { `$_.ProcessName -eq "ChronicleAndroidRawDataPreprocessingApp" } | ForEach-Object { 
            Write-Host "Killing leftover process with ID: `$(`$_.Id)"
            Stop-Process -Id `$_.Id -Force -ErrorAction SilentlyContinue
          }
          exit 1
        }
        "@
        
        Set-Content -Path "measure-startup.ps1" -Value $measureScript
        
        try {
          # Run the measurement script with a timeout
          $overallTimeout = 30  # seconds
          $job = Start-Job -ScriptBlock { pwsh -File "measure-startup.ps1" }
          
          # Wait for job with timeout
          if (Wait-Job -Job $job -Timeout $overallTimeout) {
            $result = Receive-Job -Job $job
            Write-Host $result
            
            # Check exit code from output
            if ($result -match "Test completed successfully") {
              Write-Host "Executable startup test passed!"
            } elseif ($result -match "WARNING: Startup time exceeds") {
              Write-Warning "Executable starts but startup time is high"
            } else {
              Write-Error "Failed to start executable properly"
              exit 1
            }
          } else {
            Write-Host "Overall timeout reached. Measurement script didn't complete in $overallTimeout seconds"
            Stop-Job -Job $job
            Remove-Job -Job $job -Force
            
            # Kill any remaining processes
            Get-Process | Where-Object { $_.ProcessName -eq "ChronicleAndroidRawDataPreprocessingApp" } | ForEach-Object { 
              Write-Host "Killing leftover process with ID: $($_.Id)"
              Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
            }
            
            exit 1
          }
        } catch {
          Write-Error "Error testing executable: $_"
          
          # Kill any remaining processes
          Get-Process | Where-Object { $_.ProcessName -eq "ChronicleAndroidRawDataPreprocessingApp" } | ForEach-Object { 
            Write-Host "Killing leftover process with ID: $($_.Id)"
            Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
          }
          
          exit 1
        } finally {
          Remove-Job -Job $job -Force -ErrorAction SilentlyContinue
        }
      shell: pwsh
    
    - name: Create ZIP archive
      run: |
        # Ensure build was successful
        if (Test-Path dist/ChronicleAndroidRawDataPreprocessingApp) {
          # Extract version safely from config/version.py for consistency
          try {
            $version = python -c "import re; match = re.search(r'__version__ = \"(.*)\"', [System.IO.File]::ReadAllText('config/version.py')); print(match.Groups[1].Value if match else '0.1.0')"
          } catch {
            $version = Get-Date -Format "yyyy.MM.dd"
          }
          
          # Create a temporary directory for all files
          $tempDir = "ChronicleAndroidRawDataPreprocessingApp-win-$version"
          New-Item -Path $tempDir -ItemType Directory
          
          # Copy all repository files (except .git, dist, build, etc.)
          Write-Host "Copying repository files..."
          Get-ChildItem -Path "." -Exclude ".git", ".github", "dist", "build", "__pycache__", "*.spec", "*.zip", "*.log", "measure-startup.ps1", "README.txt", $tempDir | ForEach-Object {
            if (Test-Path $_.FullName -PathType Container) {
              # Copy directories
              Copy-Item -Path $_.FullName -Destination "$tempDir/$($_.Name)" -Recurse
            } else {
              # Copy files
              Copy-Item -Path $_.FullName -Destination "$tempDir/$($_.Name)"
            }
          }
          
          # Copy the built executable files directly into the main directory
          Write-Host "Copying built executable..."
          Copy-Item -Path dist/ChronicleAndroidRawDataPreprocessingApp/* -Destination "$tempDir" -Recurse
          
          # Create ZIP with all content
          Write-Host "Creating ZIP archive..."
          Compress-Archive -Path $tempDir/* -DestinationPath "ChronicleAndroidRawDataPreprocessingApp-win-$version.zip"
          
          # Clean up temporary directory
          Remove-Item -Path $tempDir -Recurse -Force
        } else {
          Write-Error "Build directory not found. The PyInstaller build may have failed."
          exit 1
        }
      shell: pwsh
      
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-windows
        path: dist/ChronicleAndroidRawDataPreprocessingApp
        
    - name: Upload ZIP archive as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-win-zip
        path: ChronicleAndroidRawDataPreprocessingApp-win-*.zip

  build-macos:
    needs: determine-version
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Download version info
      uses: actions/download-artifact@v4
      with:
        name: version-info
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
        # Display environment info for debugging
        echo "Python version:"
        python --version
        echo "Python location: $pythonLocation"
        echo "Current directory: $(pwd)"
      
    - name: Build with PyInstaller
      run: |
        # Ensure python is in PATH
        export PATH="$pythonLocation/bin:$PATH"
        
        # Make script executable if needed
        chmod +x main.py || true
        
        # Build macOS app bundle with debug output enabled
        python -m PyInstaller --clean ChronicleAndroidRawDataPreprocessingApp.spec
        
        # Verbose output for directory contents
        echo "Contents of dist directory:"
        ls -la dist/
        
        # Verify the app bundle was created correctly
        if [ -d "dist/ChronicleAndroidRawDataPreprocessingApp.app" ]; then
          echo "App bundle created successfully"
          echo "Directory structure of the app bundle:"
          find "dist/ChronicleAndroidRawDataPreprocessingApp.app" -type f | sort
          
          # Check executable in MacOS directory
          if [ -d "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS" ]; then
            echo "Contents of MacOS directory:"
            ls -la "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS"
            
            # Verify the executable exists and is executable
            if [ -f "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS/ChronicleAndroidRawDataPreprocessingApp" ]; then
              echo "Executable found and should be runnable"
              
              # Check file permissions
              ls -l "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS/ChronicleAndroidRawDataPreprocessingApp"
              
              # Fix permissions if needed
              chmod +x "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS/ChronicleAndroidRawDataPreprocessingApp" || true
            else
              echo "ERROR: Executable not found in MacOS directory"
              exit 1
            fi
          else
            echo "ERROR: MacOS directory not found in app bundle"
            mkdir -p "dist/ChronicleAndroidRawDataPreprocessingApp.app/Contents/MacOS"
          fi
        else
          echo "ERROR: App bundle creation failed"
          echo "Contents of dist directory:"
          ls -la dist/
          exit 1
        fi
      
    - name: Create DMG package
      run: |
        # Extract version from config/version.py to ensure consistency with the rest of the build
        VERSION=$(python3 -c "import re; match = re.search(r'__version__ = \"(.*)\"', open('config/version.py').read()); print(match.group(1) if match else '0.1.0')")
        echo "Using version: $VERSION"
        
        # Create a temporary directory
        TEMP_DIR="ChronicleAndroidRawDataPreprocessingApp-mac-$VERSION"
        mkdir -p "$TEMP_DIR"
        
        # Copy repository files (except large/system directories)
        echo "Copying repository files..."
        rsync -a --exclude=".git" --exclude="dist" --exclude="build" --exclude="__pycache__" \
              --exclude="*.spec" --exclude="*.zip" --exclude="*.dmg" --exclude="*.log" \
              --exclude="README.txt" --exclude="$TEMP_DIR" \
              --exclude="node_modules" \
              . "$TEMP_DIR/"
        
        # Check if the app bundle exists and copy it
        if [ -d "dist/ChronicleAndroidRawDataPreprocessingApp.app" ]; then
          echo "Copying built application..."
          # Using ditto to preserve permissions and metadata
          ditto "dist/ChronicleAndroidRawDataPreprocessingApp.app" "$TEMP_DIR/ChronicleAndroidRawDataPreprocessingApp.app"
          
          # Verify the app was copied correctly
          if [ -d "$TEMP_DIR/ChronicleAndroidRawDataPreprocessingApp.app" ]; then
            echo "App bundle copied successfully"
          else
            echo "ERROR: App bundle copy failed"
            exit 1
          fi
        else
          echo "ERROR: App bundle not found at dist/ChronicleAndroidRawDataPreprocessingApp.app"
          ls -la dist/
          exit 1
        fi
        
        # Create DMG using hdiutil directly
        echo "Creating DMG..."
        DMG_NAME="ChronicleAndroidRawDataPreprocessingApp-mac-$VERSION.dmg"
        
        # Create temporary DMG
        hdiutil create -volname "ChronicleAndroidRawDataPreprocessingApp" \
                       -srcfolder "$TEMP_DIR" \
                       -ov -format UDRW \
                       -fs HFS+ \
                       "temp_$DMG_NAME" || { echo "Failed to create temporary DMG"; exit 1; }
        
        # Convert to compressed final DMG
        hdiutil convert "temp_$DMG_NAME" \
                        -format UDZO \
                        -o "$DMG_NAME" || { echo "Failed to convert DMG"; exit 1; }
        
        # Clean up
        rm -f "temp_$DMG_NAME"
        rm -rf "$TEMP_DIR"
        
        # Verify DMG was created
        if [ -f "$DMG_NAME" ]; then
          echo "DMG created successfully: $DMG_NAME"
          ls -la "$DMG_NAME"
          # Get file size
          du -h "$DMG_NAME"
        else
          echo "ERROR: DMG creation failed"
          exit 1
        fi
      
    - name: Upload app bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-mac-app
        path: dist/ChronicleAndroidRawDataPreprocessingApp.app
        if-no-files-found: warn
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-mac-dmg
        path: ChronicleAndroidRawDataPreprocessingApp-mac-*.dmg
        if-no-files-found: error

  release:
    needs: [determine-version, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download version info
      uses: actions/download-artifact@v4
      with:
        name: version-info
    
    - name: Download Windows ZIP artifact
      uses: actions/download-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-win-zip
        path: artifacts
    
    - name: Download macOS DMG artifact
      uses: actions/download-artifact@v4
      with:
        name: ChronicleAndroidRawDataPreprocessingApp-mac-dmg
        path: artifacts
    
    - name: List artifacts
      run: |
        echo "Available artifacts for release:"
        find artifacts -type f | sort
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ needs.determine-version.outputs.version }}
        files: |
          artifacts/ChronicleAndroidRawDataPreprocessingApp-win-*.zip
          artifacts/ChronicleAndroidRawDataPreprocessingApp-mac-*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: false 